from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'HealthRecord',
    'ReportExtraction',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'healthRecords': 'HealthRecord',
        'reports': 'ReportExtraction',
    },
    'HealthRecord': {
        'user': 'User',
        'report': 'ReportExtraction',
    },
    'ReportExtraction': {
        'user': 'User',
        'healthRecord': 'HealthRecord',
    },
}

# fmt: on